# Generated by Django 6.0.2 on 2026-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название породы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('average_weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Средний вес')),
                ('life_expectancy', models.IntegerField(verbose_name='Средняя продолжительность жизни')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
    ]
