# Generated by Django 6.0.2 on 2026-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='breeds/', verbose_name='Фото породы'),
        ),
    ]
