# Generated by Django 6.0.2 on 2026-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlibrary', '0003_breed_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название тега')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='breeds', to='catlibrary.tag', verbose_name='Теги'),
        ),
    ]
